name: Sync Gitee to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 调试环境信息
        run: |
          echo "======================================"
          echo "当前 GitHub 仓库上下文:"
          echo "GITHUB_REPOSITORY = ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER = ${{ github.repository_owner }}"
          echo "GITHUB_ACTOR = ${{ github.actor }}"
          echo "GITHUB_REF = ${{ github.ref }}"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "======================================"
          echo "您的仓库信息:"
          echo "仓库所有者 = ${{ github.repository_owner }}"
          echo "仓库名称 = geren-bokell"
          echo "完整仓库路径 = ${{ github.repository_owner }}/geren-bokell"
          echo "======================================"

      - 名字: 🔄 同步仓库
        run: |
          # 1. 克隆Gitee仓库
          git clone https://gitee.com/wzjwwcom/personal-blog.git repo
          echo "✅ 成功通过Git克隆Gitee仓库"
          
          # 2. 进入仓库目录
          cd repo
          
          # 3. 移除所有可能存在的远程配置
          git remote remove origin 2>/dev/null || true
          git remote remove github 2>/dev/null || true
          
          # 4. 使用正确的仓库URL格式（关键：确保无多余空格）
          REPO_OWNER="${{ github.repository_owner }}"
          GITHUB_URL="https://x-access-token:${{ github.token }}@github.com/$REPO_OWNER/geren-bokell.git"
          
          echo "======================================"
          echo "正在使用以下URL推送:"
          echo "$GITHUB_URL"
          echo "======================================"
          
          # 5. 配置Git用户信息
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 6. 添加GitHub远程
          git remote add origin "$GITHUB_URL"
          
          # 7. 检查远程配置
          echo "当前配置的远程仓库:"
          git remote -v
          
          # 8. 推送所有分支和标签
          git push -u origin --all --force
          git push -u origin --tags --force
