名字: Sync Gitee to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - 名字: Sync Repository
        run: |
          # 使用wget代替curl，并添加浏览器User-Agent避免触发人机验证
          wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
            -O repo.zip \
            "https://gitee.com/wzjwwcom/personal-blog/repository/archive/master.zip"
          
          # 解压并准备仓库
          unzip repo.zip
          mv personal-blog-* repo
          cd repo
          
          # 初始化新 Git 仓库
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 添加正确的 GitHub 远程
          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
          
          # 添加所有文件并提交
          git add .
          git commit -m "Sync from Gitee"
          
          # 推送到 GitHub
          git push -u origin --all --force
          git push -u origin --tags --force
